api/urls.py
from django.urls import path
from rest_framework import routers

from .viewsets import ElementReadOnlyViewSet,ElementCreateUpdateDestroyViewSet, CategoryViewSet, TypeViewSet, CommentViewSet
from . import views

route = routers.SimpleRouter()

route.register('element',ElementReadOnlyViewSet)
route.register('element2',ElementCreateUpdateDestroyViewSet)
route.register('category',CategoryViewSet)
route.register('type',TypeViewSet)
route.register('comment',CommentViewSet)

urlpatterns = route.urls

urlpatterns += path('login', views.login),

comments/urls.py
from django.urls import path
from . import views

app_name='comments'
urlpatterns = [
    path('add', views.add, name='add'),
    path('contact', views.contact, name='contact'),
    path('filter', views.filter, name='filter'),
    path('', views.index, name='index'),
    path('update/<int:pk>', views.update, name='update'),
    path('delete/<int:pk>', views.delete, name='delete')
]

mystore/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    # path("", include("elements.urls"))
    path("tasks/", include("comments.urls")),
    path("elements/", include("elements.urls")),
    path("api/", include("api.urls")),
]

comments/models.py
from django.db import models

from elements.models import Element

# Create your models here.
class Comment(models.Model):
    text = models.TextField()
    date_posted = models.DateTimeField(auto_now=True)
    element = models.ForeignKey(Element, on_delete=models.CASCADE, null=True, related_name='comments')

    def __str__(self) -> str:
        return 'Comment #{}'.format(self.id)

comments/forms.py
from django.contrib.admin.widgets import BaseAdminDateWidget, BaseAdminTimeWidget 
from django.forms import ModelForm
from django import forms

from .models import Comment

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
 

class OtherWidget(forms.TextInput):
    
    class Media:
        css = {
            "all": ["other.css"],
        }
        js = ["other.js"]

class CalendarWidget(forms.TextInput):
    
    class Media:
        css = {
            "all": ["pretty.css"],
        }
        js = ["animations.js", 'actions.js']

class CustomTextInput(forms.TextInput):
    icon=''

    def __init__(self, icon=''):
        self.icon = icon
        super().__init__()

    class Media:
        css = {
            "all": ["pretty.css"],
        }
        js = ["animations.js", 'actions.js']

    def render(self, name, value, attrs=None, renderer=None):
        
        if self.icon:
            return f'<div class="group"><img src="{self.icon}"> {super().render(name, value, attrs, renderer)} </div>'
        else:
            return super().render(name, value, attrs, renderer)



class ContactForm(forms.Form):
    other = forms.CharField(widget=OtherWidget, help_text='Help text 1')
    calendar = forms.CharField(widget=BaseAdminDateWidget, help_text='Help text 4')
    custom = forms.CharField(widget=CustomTextInput(icon='user.png'), help_text='Help text 2')

comments/views.py
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from django.core.paginator import Paginator
from django.http import Http404

from .models import Comment
from .forms import CommentForm, ContactForm

# Create your views here.
def add(request):
    if(request.method == 'POST'):
        form = CommentForm(request.POST)
        form.save()
        return redirect('comments:index')
    else:
        #GET
        form = CommentForm()
    return render(request, 'comments/add.html', {'form':form})
# def add(request):
#     if(request.method == 'GET'):
#         pass
#     if(request.method == 'POST'):
#         #save
#         if request.POST.get('text') != '':
#             comment = Comment()
#             comment.text = request.POST.get('text')
#             comment.save()
#         else: 
#             print('Campo es vacio')

#     return render(request, 'add.html')

def index(request):
    comments = Comment.objects.all()
    # comments = get_list_or_404(Comment, pk__gt=14)
    paginator = Paginator(comments,2)

    page_number = request.GET.get('page')
    comments_page = paginator.get_page(page_number)

    return render(request, 'comments/index.html', {'comments': comments_page})

def update(request, pk):

    comment = get_object_or_404(Comment,pk=pk)

    # try:
    #     comment = Comment.objects.get(pk=pk)
    # except Comment.DoesNotExist:
    #     raise Http404

    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
    
        if form.is_valid():
            form.save()
            return redirect('comments:index')
    else:
        form = CommentForm(instance=comment)
        
    return render(request, 'comments/add.html', {'form':form, 'comment':comment })

def delete(request, pk):
    # comment = Comment.objects.get(pk=pk)
    comment = Comment.objects.get(pk=pk)


    if request.method == 'POST':
        comment.delete()
        return redirect('comments:index')
    

def contact(request):
    
    form = ContactForm()
    return render(request, 'comments/contact.html', {'form':form})

def filter(request):
    contentHTML = '<button type="button">Send</button>'
    return render(request, 'comments/filter.html', { 'array': [1,2,3,4,5,6], 'contentHTML': contentHTML})

comments/templates/comments/add.html
{% extends "base.html" %}

{% block content %}

    <h1>Page to add</h1>

    {{ comment.date_posted|date:"D d M Y" }}

    {% with date=comment.date_posted %}
        {{ comment.date_posted }}
    {% endwith %}

    {% include "partials/errors-form.html" %}

    {% comment %} <form action="add" method="POST">
      
        <label for="">Text:</label>
        <textarea required name="text"></textarea>
        {% csrf_token %}
        <button type="submit">Send</button>
    </form> {% endcomment %}

    <form action="" method="post">
        {{ form.text }}
        {% csrf_token %}
        <button type="submit">Send</button>
    </form>
{% endblock %}

comments/templates/comments/contact copy.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {{ form.media }}
</head>
<body>

    <form action="" method="post">
        {{ form.other }}
        {{ form.calendar }}
        
        {% autoescape off %}
            {{ form.custom }}
        {% endautoescape %}

        {% csrf_token %}
        <button type="submit">Send</button>
    </form>
    


</body>
</html>

comments/templates/comments/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link rel="stylesheet" href="/static/admin/css/forms.css">

    <script src="/admin/jsi18n/"></script>
    <script src="/static/admin/js/core.js"></script>
    {{ form.media }}
</head>
<body>

    <form action="" method="post">
  
        {{ form.other.as_field_group }}
        {{ form.calendar.as_field_group }}
        
        {% autoescape off %}
            {{ form.custom.as_field_group }}
        {% endautoescape %}


        {% csrf_token %}
        <button type="submit">Send</button>
    </form>
    


</body>
</html>

comments/templates/comments/filter.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h3>Filtros</h3>

    {% load custom_tags %}

    <p>{% now "jS F Y H:i" %}</p>

    <p>{{ "AndRes"|lower }}</p>
    <p>{{ "AndRes"|upper }}</p>
    <p>{{ 5|add:"6" }}</p>

    {% for a in array %}
        <div class="{% cycle 'row1' 'row2' 'row3' %} other">

        </div>
    {% endfor %}

    <p>{{ array|default:'nothing' }}</p>

    <p>{{ array|length }}</p>

    <p>{{ 'Andres'|length }}</p>

    {{ '<button type="button">Send</button>' }}
    {{ '<button type="button">Send</button>'|safe }}
    {{ contentHTML }}
    {{ contentHTML|safe }}

    <p>{{ array|join:'-' }}</p>

    <p>{{ "andres"|my_name:"cruz" }}</p>

</body>
</html>

comments/templates/comments/index.html
{% extends "base.html" %}

{% load custom_tags %}

{% block content %}

    {% my_connection "table" "C1" %}

    {{ "andres29@gmail.com"|cut:"gmail." }}

    <a href="{% url 'comments:add' %}" target="_blank">Add</a>

    {% for c in comments %}
        <p>{{ c.text|cut:"!"|safe }}</p>
        <hr>
        <p>{{ c.date_posted }}</p>
        <!-- <a href="/tasks/update/{{ c.id }}">Edit</a> -->
        <a href="{% url 'comments:update' c.id %}">Edit</a>
        <form action="{% url 'comments:delete' c.id %}" method="post">
            {% csrf_token %}
            <input type="submit" value="Delete">
        </form>
    {% endfor %}

    <nav>
        <ul class="pagination justify-content-center">
            {% if  comments.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ comments.previous_page_number }}">Prev</a>
                </li>
            {% endif %}
               
                 <li class="page-item">
                    {% for i in comments.paginator.page_range  %}
                        {% if i == comments.number %}
                            <a href="?page={{ i }}" class="page-link active">
                                {{i}}
                            </a>
                        {% else %}
                            <a href="?page={{ i }}" class="page-link">
                                {{i}}
                            </a>
                        {% endif %}
                    {% endfor %}
                </li>

            {% if comments.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ comments.next_page_number }}">Next</a>
                </li>
            {% endif %}


   


        </ul>
    </nav>
    

    

{% endblock %}